### ISSUE TITLE
Corrections in Method paradigms

### ISSUE THREAD

**Issue by santoshTYSS** [zjunlp/KnowledgeEditingPapers#13]
I have noticed two possible corrections of papers and their taxonomy.

(i) WISE: Rethinking the Knowledge Memory for Lifelong Model Editing of Large Language Models. 
Currently, this is listed in memory-based, but this should be in Additional Parameters as they introduce side memory in addition to main memory

(ii) WilKE: Wise-Layer Knowledge Editor for Lifelong Knowledge Editing
This is listed under Preserve Parameters -> Additional Parameters; But this altogether deals with Modify Parameters and more explicitly under locate and edit under modify parameters.

Can you please clarify them, if I misunderstood them.

**Comment by zxlzr** [comment]
Thank you  very much for your suggestions, we will soon fix and update the repo.

**Comment by XeeKee** [comment]
Thank you very much for your suggestion. We have made the necessary changes.
