### ISSUE TITLE
One more paper may be added: "SafeInfer: Context Adaptive Decoding Time Safety Alignment for Large Language Models"

### ISSUE THREAD

**Issue by RadiantCrystal** [zjunlp/KnowledgeEditingPapers#14]
Hello Maintainers,

Thanks for maintaining this vast and extensive list of recent papers!

I feel **SafeInfer** could be a potential relevant work on LLM safety alignment for base and edited models. You may categorize it in 'more related papers'.

Check out our work at [SafeInfer: Context Adaptive Decoding Time Safety Alignment for Large Language Models](https://arxiv.org/abs/2406.12274).

**Comment by xzwyyd** [comment]
Thanks for your advice, and I have added it to our paper lists.
