### ISSUE TITLE
Add New work ”Intrinsic Evaluation of Unlearning Using Parametric Knowledge Traces“.

### ISSUE THREAD

**Issue by yihuaihong** [zjunlp/KnowledgeEditingPapers#16]
Hi, Dear manager, 
I would like to know whether you would be willing to add our new paper: **Intrinsic Evaluation of Unlearning Using Parametric Knowledge Traces**.
We believe that the knowledge vectors we have identified, their verified importance in storing target knowledge, and the corresponding analysis have significant implications for both unlearning and knowledge editing areas. I would suggest placing it under the Analysis Section and Benchmark Section.

Thank you very much for your kindness!

paper: https://arxiv.org/pdf/2406.11614
code: https://github.com/yihuaihong/ConceptVectors
website: https://yihuaihong.github.io/ConceptVectors.github.io

**Comment by mengrusun** [comment]
Thank you for your suggestions.

Your work highlights the challenge and importance of erasing learned concepts in LLMs, which has significant implications for both unlearning and knowledge editing areas. We have placed your work under the Analysis Section and Benchmark Section.

If you have any further advice or discussions, please contact us anytime.

**Comment by yihuaihong** [comment]
Thank you very much! 😀
